"""member tg_user_id nullable (участники без Telegram)

Revision ID: c6ba57efc203
Revises: 9098794c7b2f
Create Date: 2026-09-04 18:10:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ba57efc203'
down_revision: Union[str, None] = '9098794c7b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # tg_user_id теперь может быть NULL — это участник, добавленный вручную (без Telegram-
    # аккаунта, например ребёнок или родственник без своего профиля). Уникальность
    # (chat_id, tg_user_id) не страдает: и SQLite, и Postgres не считают NULL равным NULL
    # в UNIQUE-констрейнте, так что несколько ручных участников в одном чате не конфликтуют.
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('tg_user_id', existing_type=sa.BigInteger(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('tg_user_id', existing_type=sa.BigInteger(), nullable=False)

    # ### end Alembic commands ###
